project:
  type: website
  output-dir: docs

website:
  title: "Diya Jiang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd

format:
  html:
    theme: Litera
    css: styles.css
    toc: true

editor: visual

